"""
Built-in policy templates for common governance scenarios.

Includes:
- General cloud governance policies
- BIO (Baseline Informatiebeveiliging Overheid) compliance policies
- PQC (Post-Quantum Cryptography) readiness policies
"""

from itl_policy_builder.templates.general import (
    get_builtin_policy,
    list_builtin_policies,
    get_all_builtin_policies,
    AllowedLocationsPolicy,
    RequireTagPolicy,
    AuditMissingTagPolicy,
    AllowedResourceTypesPolicy,
    DenyPublicIPPolicy,
    RequireNetworkSecurityGroupPolicy,
)

from itl_policy_builder.templates.bio import (
    get_bio_policy,
    list_bio_policies,
    get_all_bio_policies,
    get_bio_policies_by_category,
    get_bio_initiative,
    BIO_CATEGORIES,
    # BIO Policy Classes
    RequireDataClassificationPolicy,
    RequireOwnerTagPolicy,
    DenyAnonymousAccessPolicy,
    RequireEncryptionAtRestPolicy,
    RequireEncryptionInTransitPolicy,
    RequireDiagnosticLogsPolicy,
    DenyPublicEndpointsPolicy,
    RequireNSGPolicy as BIORequireNSGPolicy,
    DenyRDPFromInternetPolicy,
    AllowedLocationsNLPolicy,
)

from itl_policy_builder.templates.pqc import (
    get_pqc_policy,
    list_pqc_policies,
    get_all_pqc_policies,
    get_pqc_policies_by_category,
    get_pqc_initiative,
    get_pqc_transition_initiative,
    PQC_CATEGORIES,
    NIST_PQC_KEMs,
    NIST_PQC_SIGNATURES,
    HYBRID_KEMs,
    HYBRID_SIGNATURES,
    DEPRECATED_ALGORITHMS,
    # PQC Policy Classes
    RequirePQCKeyExchangePolicy,
    RequirePQCSignaturePolicy,
    DenyDeprecatedAlgorithmsPolicy,
    RequireHybridModePolicy,
    RequirePQCKeyVaultPolicy,
    RequirePQCTLSPolicy,
    RequirePQCCertificatesPolicy,
    RequirePQCReadinessTagPolicy,
    AuditClassicalCryptoPolicy,
)

from itl_policy_builder.templates.cis_azure import (
    get_cis_policy,
    list_cis_policies,
    get_all_cis_policies,
    get_cis_policies_by_section,
    get_cis_policies_by_severity,
    get_cis_initiative,
    get_cis_high_severity_initiative,
    CIS_SECTIONS,
    CIS_BENCHMARK_VERSION,
    CIS_BENCHMARK_REFERENCE,
    # CIS Policy Classes
    RequireSecurityContactEmailPolicy,
    RequireMFATagPolicy as CISRequireMFATagPolicy,
    DenyGuestUserOwnerRolePolicy,
    RequireDefenderForServersPolicy,
    RequireDefenderTagPolicy,
    RequireStorageSecureTransferPolicy,
    DenyStoragePublicBlobAccessPolicy,
    RequireStorageMinTLSPolicy,
    RequireStorageNetworkDefaultDenyPolicy,
    RequireSQLAuditingPolicy,
    RequireSQLTDEPolicy,
    RequireSQLMinTLSPolicy,
    RequireSQLPublicAccessDisabledPolicy,
    RequireActivityLogRetentionPolicy,
    RequireDiagnosticSettingsPolicy,
    DenyPublicStorageForLogsPolicy,
    DenyRDPFromInternetPolicy as CISDenyRDPFromInternetPolicy,
    DenySSHFromInternetPolicy,
    RequireNSGOnSubnetsPolicy,
    RequireNSGFlowLogsPolicy,
    RequireVMDiskEncryptionPolicy,
    RequireVMDataDiskEncryptionPolicy,
    RequireTrustedLaunchPolicy,
    RequireKeyExpiryPolicy,
    RequireSecretExpiryPolicy,
    RequireKeyVaultRecoverablePolicy,
    RequireKeyVaultFirewallPolicy,
    RequireKeyVaultRBACPolicy,
    # CIS Section 9: App Service
    RequireAppServiceAuthPolicy,
    RequireHTTPSOnlyAppServicePolicy,
    RequireLatestTLSAppServicePolicy,
    RequireManagedIdentityAppServicePolicy,
    RequireLatestHTTPVersionAppServicePolicy,
    RequireFTPSOnlyAppServicePolicy,
    RequireKeyVaultForAppSecretsPolicy,
    # AKS
    RequireAKSRBACPolicy,
    RequireAKSAuthorizedIPRangesPolicy,
    RequireAKSPrivateClusterPolicy,
    RequireAKSDefenderPolicy,
    DenyAKSPrivilegedContainersPolicy,
    RequireAKSNetworkPolicyPolicy,
    # Container Registry (ACR)
    DenyACRAdminUserPolicy,
    RequireACRPrivateEndpointPolicy,
    RequireACRImageScanPolicy,
    # Application Gateway & WAF
    RequireWAFOnAppGatewayPolicy,
    RequireWAFPreventionModePolicy,
    RequireWAFPolicyLinkPolicy,
    # Backup & Recovery
    RequireBackupSoftDeletePolicy,
    RequireVMBackupPolicy,
    RequireBackupImmutabilityPolicy,
    # Log Analytics
    RequireLogAnalyticsRetentionPolicy,
    DenyLogAnalyticsPublicAccessPolicy,
    RequireLogAnalyticsCMKPolicy,
    # Cosmos DB
    RequireCosmosFirewallPolicy,
    DenyCosmosPublicNetworkPolicy,
    RequireCosmosCMKPolicy,
    # Governance & Tagging
    RequireEnvironmentTagPolicy,
    RequireCostCenterTagPolicy,
    RequireOwnerTagGovPolicy,
    RequireAllowedLocationsPolicy,
)

__all__ = [
    # General
    "get_builtin_policy",
    "list_builtin_policies",
    "get_all_builtin_policies",
    "AllowedLocationsPolicy",
    "RequireTagPolicy",
    "AuditMissingTagPolicy",
    "AllowedResourceTypesPolicy",
    "DenyPublicIPPolicy",
    "RequireNetworkSecurityGroupPolicy",
    # BIO
    "get_bio_policy",
    "list_bio_policies",
    "get_all_bio_policies",
    "get_bio_policies_by_category",
    "get_bio_initiative",
    "BIO_CATEGORIES",
    # BIO Policy Classes
    "RequireDataClassificationPolicy",
    "RequireOwnerTagPolicy",
    "DenyAnonymousAccessPolicy",
    "RequireEncryptionAtRestPolicy",
    "RequireEncryptionInTransitPolicy",
    "RequireDiagnosticLogsPolicy",
    "DenyPublicEndpointsPolicy",
    "BIORequireNSGPolicy",
    "DenyRDPFromInternetPolicy",
    "AllowedLocationsNLPolicy",
    # PQC
    "get_pqc_policy",
    "list_pqc_policies",
    "get_all_pqc_policies",
    "get_pqc_policies_by_category",
    "get_pqc_initiative",
    "get_pqc_transition_initiative",
    "PQC_CATEGORIES",
    "NIST_PQC_KEMs",
    "NIST_PQC_SIGNATURES",
    "HYBRID_KEMs",
    "HYBRID_SIGNATURES",
    "DEPRECATED_ALGORITHMS",
    # PQC Policy Classes
    "RequirePQCKeyExchangePolicy",
    "RequirePQCSignaturePolicy",
    "DenyDeprecatedAlgorithmsPolicy",
    "RequireHybridModePolicy",
    "RequirePQCKeyVaultPolicy",
    "RequirePQCTLSPolicy",
    "RequirePQCCertificatesPolicy",
    "RequirePQCReadinessTagPolicy",
    "AuditClassicalCryptoPolicy",
    # CIS Azure
    "get_cis_policy",
    "list_cis_policies",
    "get_all_cis_policies",
    "get_cis_policies_by_section",
    "get_cis_policies_by_severity",
    "get_cis_initiative",
    "get_cis_high_severity_initiative",
    "CIS_SECTIONS",
    "CIS_BENCHMARK_VERSION",
    "CIS_BENCHMARK_REFERENCE",
    # CIS Policy Classes
    "RequireSecurityContactEmailPolicy",
    "CISRequireMFATagPolicy",
    "DenyGuestUserOwnerRolePolicy",
    "RequireDefenderForServersPolicy",
    "RequireDefenderTagPolicy",
    "RequireStorageSecureTransferPolicy",
    "DenyStoragePublicBlobAccessPolicy",
    "RequireStorageMinTLSPolicy",
    "RequireStorageNetworkDefaultDenyPolicy",
    "RequireSQLAuditingPolicy",
    "RequireSQLTDEPolicy",
    "RequireSQLMinTLSPolicy",
    "RequireSQLPublicAccessDisabledPolicy",
    "RequireActivityLogRetentionPolicy",
    "RequireDiagnosticSettingsPolicy",
    "DenyPublicStorageForLogsPolicy",
    "CISDenyRDPFromInternetPolicy",
    "DenySSHFromInternetPolicy",
    "RequireNSGOnSubnetsPolicy",
    "RequireNSGFlowLogsPolicy",
    "RequireVMDiskEncryptionPolicy",
    "RequireVMDataDiskEncryptionPolicy",
    "RequireTrustedLaunchPolicy",
    "RequireKeyExpiryPolicy",
    "RequireSecretExpiryPolicy",
    "RequireKeyVaultRecoverablePolicy",
    "RequireKeyVaultFirewallPolicy",
    "RequireKeyVaultRBACPolicy",
    # CIS Section 9: App Service
    "RequireAppServiceAuthPolicy",
    "RequireHTTPSOnlyAppServicePolicy",
    "RequireLatestTLSAppServicePolicy",
    "RequireManagedIdentityAppServicePolicy",
    "RequireLatestHTTPVersionAppServicePolicy",
    "RequireFTPSOnlyAppServicePolicy",
    "RequireKeyVaultForAppSecretsPolicy",
    # AKS
    "RequireAKSRBACPolicy",
    "RequireAKSAuthorizedIPRangesPolicy",
    "RequireAKSPrivateClusterPolicy",
    "RequireAKSDefenderPolicy",
    "DenyAKSPrivilegedContainersPolicy",
    "RequireAKSNetworkPolicyPolicy",
    # Container Registry (ACR)
    "DenyACRAdminUserPolicy",
    "RequireACRPrivateEndpointPolicy",
    "RequireACRImageScanPolicy",
    # Application Gateway & WAF
    "RequireWAFOnAppGatewayPolicy",
    "RequireWAFPreventionModePolicy",
    "RequireWAFPolicyLinkPolicy",
    # Backup & Recovery
    "RequireBackupSoftDeletePolicy",
    "RequireVMBackupPolicy",
    "RequireBackupImmutabilityPolicy",
    # Log Analytics
    "RequireLogAnalyticsRetentionPolicy",
    "DenyLogAnalyticsPublicAccessPolicy",
    "RequireLogAnalyticsCMKPolicy",
    # Cosmos DB
    "RequireCosmosFirewallPolicy",
    "DenyCosmosPublicNetworkPolicy",
    "RequireCosmosCMKPolicy",
    # Governance & Tagging
    "RequireEnvironmentTagPolicy",
    "RequireCostCenterTagPolicy",
    "RequireOwnerTagGovPolicy",
    "RequireAllowedLocationsPolicy",
]
