"""
Built-in policy templates for common governance scenarios.

Includes:
- General cloud governance policies
- BIO (Baseline Informatiebeveiliging Overheid) compliance policies
- PQC (Post-Quantum Cryptography) readiness policies
- Managed Identity and Workload Identity enforcement
- CIS Azure Foundations Benchmark policies
"""

from itl_policy_builder.templates.general import (
    get_builtin_policy,
    list_builtin_policies,
    get_all_builtin_policies,
    AllowedLocationsPolicy,
    RequireTagPolicy,
    AuditMissingTagPolicy,
    AllowedResourceTypesPolicy,
    DenyPublicIPPolicy,
    RequireNetworkSecurityGroupPolicy,
)

from itl_policy_builder.templates.bio import (
    get_bio_policy,
    list_bio_policies,
    get_all_bio_policies,
    get_bio_policies_by_category,
    get_bio_initiative,
    BIO_CATEGORIES,
    # BIO Policy Classes
    RequireDataClassificationPolicy,
    RequireOwnerTagPolicy,
    DenyAnonymousAccessPolicy,
    RequireEncryptionAtRestPolicy,
    RequireEncryptionInTransitPolicy,
    RequireDiagnosticLogsPolicy,
    DenyPublicEndpointsPolicy,
    RequireNSGPolicy as BIORequireNSGPolicy,
    DenyRDPFromInternetPolicy,
    AllowedLocationsNLPolicy,
)

from itl_policy_builder.templates.pqc import (
    get_pqc_policy,
    list_pqc_policies,
    get_all_pqc_policies,
    get_pqc_policies_by_category,
    get_pqc_initiative,
    get_pqc_transition_initiative,
    PQC_CATEGORIES,
    NIST_PQC_KEMs,
    NIST_PQC_SIGNATURES,
    HYBRID_KEMs,
    HYBRID_SIGNATURES,
    DEPRECATED_ALGORITHMS,
    # PQC Policy Classes
    RequirePQCKeyExchangePolicy,
    RequirePQCSignaturePolicy,
    DenyDeprecatedAlgorithmsPolicy,
    RequireHybridModePolicy,
    RequirePQCKeyVaultPolicy,
    RequirePQCTLSPolicy,
    RequirePQCCertificatesPolicy,
    RequirePQCReadinessTagPolicy,
    AuditClassicalCryptoPolicy,
)

from itl_policy_builder.templates.managed_identity import (
    get_managed_identity_policy,
    list_managed_identity_policies,
    get_all_managed_identity_policies,
    get_managed_identity_initiative,
    create_subscription_assignment,
    MANAGED_IDENTITY_CATEGORY,
    MANAGED_IDENTITY_RESOURCE_TYPES,
    # Managed Identity Policy Classes
    DenyPasswordCredentialsPolicy,
    DenyCertificateCredentialsPolicy,
    AuditLegacyCredentialsPolicy,
    RequireManagedIdentityPolicy,
    AllowWorkloadIdentityPolicy,
)

from itl_policy_builder.templates.cis_azure import (
    get_cis_policy,
    list_cis_policies,
    get_all_cis_policies,
    get_cis_policies_by_section,
    get_cis_policies_by_severity,
    get_cis_initiative,
    get_cis_high_severity_initiative,
    CIS_SECTIONS,
    CIS_BENCHMARK_VERSION,
    CIS_BENCHMARK_REFERENCE,
    # CIS Policy Classes
    RequireSecurityContactEmailPolicy,
    RequireMFATagPolicy as CISRequireMFATagPolicy,
    DenyGuestUserOwnerRolePolicy,
    RequireDefenderForServersPolicy,
    RequireDefenderTagPolicy,
    RequireStorageSecureTransferPolicy,
    DenyStoragePublicBlobAccessPolicy,
    RequireStorageMinTLSPolicy,
    RequireStorageNetworkDefaultDenyPolicy,
    RequireSQLAuditingPolicy,
    RequireSQLTDEPolicy,
    RequireSQLMinTLSPolicy,
    RequireSQLPublicAccessDisabledPolicy,
    RequireActivityLogRetentionPolicy,
    RequireDiagnosticSettingsPolicy,
    DenyPublicStorageForLogsPolicy,
    DenyRDPFromInternetPolicy as CISDenyRDPFromInternetPolicy,
    DenySSHFromInternetPolicy,
    RequireNSGOnSubnetsPolicy,
    RequireNSGFlowLogsPolicy,
    RequireVMDiskEncryptionPolicy,
    RequireVMDataDiskEncryptionPolicy,
    RequireTrustedLaunchPolicy,
    RequireKeyExpiryPolicy,
    RequireSecretExpiryPolicy,
    RequireKeyVaultRecoverablePolicy,
    RequireKeyVaultFirewallPolicy,
    RequireKeyVaultRBACPolicy,
    # CIS Section 9: App Service
    RequireAppServiceAuthPolicy,
    RequireHTTPSOnlyAppServicePolicy,
    RequireLatestTLSAppServicePolicy,
    RequireManagedIdentityAppServicePolicy,
    RequireLatestHTTPVersionAppServicePolicy,
    RequireFTPSOnlyAppServicePolicy,
    RequireKeyVaultForAppSecretsPolicy,
    # AKS
    RequireAKSRBACPolicy,
    RequireAKSAuthorizedIPRangesPolicy,
    RequireAKSPrivateClusterPolicy,
    RequireAKSDefenderPolicy,
    DenyAKSPrivilegedContainersPolicy,
    RequireAKSNetworkPolicyPolicy,
    # Container Registry (ACR)
    DenyACRAdminUserPolicy,
    RequireACRPrivateEndpointPolicy,
    RequireACRImageScanPolicy,
    # Application Gateway & WAF
    RequireWAFOnAppGatewayPolicy,
    RequireWAFPreventionModePolicy,
    RequireWAFPolicyLinkPolicy,
    # Backup & Recovery
    RequireBackupSoftDeletePolicy,
    RequireVMBackupPolicy,
    RequireBackupImmutabilityPolicy,
    # Log Analytics
    RequireLogAnalyticsRetentionPolicy,
    DenyLogAnalyticsPublicAccessPolicy,
    RequireLogAnalyticsCMKPolicy,
    # Cosmos DB
    RequireCosmosFirewallPolicy,
    DenyCosmosPublicNetworkPolicy,
    RequireCosmosCMKPolicy,
    # Governance & Tagging
    RequireEnvironmentTagPolicy,
    RequireCostCenterTagPolicy,
    RequireOwnerTagGovPolicy,
    RequireAllowedLocationsPolicy,
)

__all__ = [
    # General
    "get_builtin_policy",
    "list_builtin_policies",
    "get_all_builtin_policies",
    "AllowedLocationsPolicy",
    "RequireTagPolicy",
    "AuditMissingTagPolicy",
    "AllowedResourceTypesPolicy",
    "DenyPublicIPPolicy",
    "RequireNetworkSecurityGroupPolicy",
    # BIO
    "get_bio_policy",
    "list_bio_policies",
    "get_all_bio_policies",
    "get_bio_policies_by_category",
    "get_bio_initiative",
    "BIO_CATEGORIES",
    # BIO Policy Classes
    "RequireDataClassificationPolicy",
    "RequireOwnerTagPolicy",
    "DenyAnonymousAccessPolicy",
    "RequireEncryptionAtRestPolicy",
    "RequireEncryptionInTransitPolicy",
    "RequireDiagnosticLogsPolicy",
    "DenyPublicEndpointsPolicy",
    "BIORequireNSGPolicy",
    "DenyRDPFromInternetPolicy",
    "AllowedLocationsNLPolicy",
    # PQC
    "get_pqc_policy",
    "list_pqc_policies",
    "get_all_pqc_policies",
    "get_pqc_policies_by_category",
    "get_pqc_initiative",
    "get_pqc_transition_initiative",
    "PQC_CATEGORIES",
    "NIST_PQC_KEMs",
    "NIST_PQC_SIGNATURES",
    "HYBRID_KEMs",
    "HYBRID_SIGNATURES",
    "DEPRECATED_ALGORITHMS",
    # PQC Policy Classes
    "RequirePQCKeyExchangePolicy",
    "RequirePQCSignaturePolicy",
    "DenyDeprecatedAlgorithmsPolicy",
    "RequireHybridModePolicy",
    "RequirePQCKeyVaultPolicy",
    "RequirePQCTLSPolicy",
    "RequirePQCCertificatesPolicy",
    "RequirePQCReadinessTagPolicy",
    "AuditClassicalCryptoPolicy",
    # CIS Azure
    "get_cis_policy",
    "list_cis_policies",
    "get_all_cis_policies",
    "get_cis_policies_by_section",
    "get_cis_policies_by_severity",
    "get_cis_initiative",
    "get_cis_high_severity_initiative",
    "CIS_SECTIONS",
    "CIS_BENCHMARK_VERSION",
    "CIS_BENCHMARK_REFERENCE",
    # CIS Policy Classes
    "RequireSecurityContactEmailPolicy",
    "CISRequireMFATagPolicy",
    "DenyGuestUserOwnerRolePolicy",
    "RequireDefenderForServersPolicy",
    "RequireDefenderTagPolicy",
    "RequireStorageSecureTransferPolicy",
    "DenyStoragePublicBlobAccessPolicy",
    "RequireStorageMinTLSPolicy",
    "RequireStorageNetworkDefaultDenyPolicy",
    "RequireSQLAuditingPolicy",
    "RequireSQLTDEPolicy",
    "RequireSQLMinTLSPolicy",
    "RequireSQLPublicAccessDisabledPolicy",
    "RequireActivityLogRetentionPolicy",
    "RequireDiagnosticSettingsPolicy",
    "DenyPublicStorageForLogsPolicy",
    "CISDenyRDPFromInternetPolicy",
    "DenySSHFromInternetPolicy",
    "RequireNSGOnSubnetsPolicy",
    "RequireNSGFlowLogsPolicy",
    "RequireVMDiskEncryptionPolicy",
    "RequireVMDataDiskEncryptionPolicy",
    "RequireTrustedLaunchPolicy",
    "RequireKeyExpiryPolicy",
    "RequireSecretExpiryPolicy",
    "RequireKeyVaultRecoverablePolicy",
    "RequireKeyVaultFirewallPolicy",
    "RequireKeyVaultRBACPolicy",
    # CIS Section 9: App Service
    "RequireAppServiceAuthPolicy",
    "RequireHTTPSOnlyAppServicePolicy",
    "RequireLatestTLSAppServicePolicy",
    "RequireManagedIdentityAppServicePolicy",
    "RequireLatestHTTPVersionAppServicePolicy",
    "RequireFTPSOnlyAppServicePolicy",
    "RequireKeyVaultForAppSecretsPolicy",
    # AKS
    "RequireAKSRBACPolicy",
    "RequireAKSAuthorizedIPRangesPolicy",
    "RequireAKSPrivateClusterPolicy",
    "RequireAKSDefenderPolicy",
    "DenyAKSPrivilegedContainersPolicy",
    "RequireAKSNetworkPolicyPolicy",
    # Container Registry (ACR)
    "DenyACRAdminUserPolicy",
    "RequireACRPrivateEndpointPolicy",
    "RequireACRImageScanPolicy",
    # Application Gateway & WAF
    "RequireWAFOnAppGatewayPolicy",
    "RequireWAFPreventionModePolicy",
    "RequireWAFPolicyLinkPolicy",
    # Backup & Recovery
    "RequireBackupSoftDeletePolicy",
    "RequireVMBackupPolicy",
    "RequireBackupImmutabilityPolicy",
    # Log Analytics
    "RequireLogAnalyticsRetentionPolicy",
    "DenyLogAnalyticsPublicAccessPolicy",
    "RequireLogAnalyticsCMKPolicy",
    # Cosmos DB
    "RequireCosmosFirewallPolicy",
    "DenyCosmosPublicNetworkPolicy",
    "RequireCosmosCMKPolicy",
    # Governance & Tagging
    "RequireEnvironmentTagPolicy",
    "RequireCostCenterTagPolicy",
    "RequireOwnerTagGovPolicy",
    "RequireAllowedLocationsPolicy",
    # Managed Identity
    "get_managed_identity_policy",
    "list_managed_identity_policies",
    "get_all_managed_identity_policies",
    "get_managed_identity_initiative",
    "create_subscription_assignment",
    "MANAGED_IDENTITY_CATEGORY",
    "MANAGED_IDENTITY_RESOURCE_TYPES",
    "DenyPasswordCredentialsPolicy",
    "DenyCertificateCredentialsPolicy",
    "AuditLegacyCredentialsPolicy",
    "RequireManagedIdentityPolicy",
    "AllowWorkloadIdentityPolicy",
]

from itl_policy_builder.templates.kyverno import (
    # Base class
    KyvernoPolicyTemplate,
    # Policy classes
    PodSecurityBaselinePolicy,
    PodSecurityRestrictedPolicy,
    RequireResourceLimitsPolicy,
    RequireApprovedRegistryPolicy,
    DisallowLatestTagPolicy,
    RequireNetworkPoliciesPolicy,
    DisallowPrivilegedPolicy,
    RequirePVCPolicy,
    PQCCryptographyReadinessPolicy,
    PQCCertificateDurationPolicy,
    TalosSecurityHardeningPolicy,
    RequireTalosLabelPolicy,
    RequireStandardLabelsPolicy,
    RequirePodDisruptionBudgetPolicy,
    # Registry & categories
    _KYVERNO_POLICIES,
    KYVERNO_CATEGORIES,
    KYVERNO_PROFILE_CATEGORIES,
    KYVERNO_POLICY_TEMPLATES,
    # Policy helpers
    get_kyverno_policy,
    list_kyverno_policies,
    get_all_kyverno_policies,
    get_kyverno_policies_by_category,
    # Profile builder functions (Kyverno equivalent of initiatives)
    get_security_profile,
    get_network_profile,
    get_registry_profile,
    get_strict_profile,
    get_talos_profile,
    get_pqc_profile,
    get_all_profile,
    _KYVERNO_PROFILE_BUILDERS,
    get_profile,
    list_profiles,
    get_profile_policies,
    # Bundle convenience functions
    get_talos_security_bundle,
    get_pqc_transition_bundle,
    # Backward-compat standalone function shims
    get_pod_security_baseline,
    get_pod_security_restricted,
    get_require_resource_limits,
    get_require_image_registry,
    get_require_image_tag,
    get_require_network_policies,
    get_disallow_privileged_containers,
    get_require_persistent_volume_claim,
    get_pqc_cryptography_readiness,
    get_pqc_certificate_duration,
    get_talos_cluster_security,
    get_require_talos_label,
    get_require_resource_labels,
    get_require_pod_disruption_budget,
)

__all__ += [
    # Kyverno base class
    "KyvernoPolicyTemplate",
    # Kyverno policy classes
    "PodSecurityBaselinePolicy",
    "PodSecurityRestrictedPolicy",
    "RequireResourceLimitsPolicy",
    "RequireApprovedRegistryPolicy",
    "DisallowLatestTagPolicy",
    "RequireNetworkPoliciesPolicy",
    "DisallowPrivilegedPolicy",
    "RequirePVCPolicy",
    "PQCCryptographyReadinessPolicy",
    "PQCCertificateDurationPolicy",
    "TalosSecurityHardeningPolicy",
    "RequireTalosLabelPolicy",
    "RequireStandardLabelsPolicy",
    "RequirePodDisruptionBudgetPolicy",
    # Registries & categories
    "_KYVERNO_POLICIES",
    "KYVERNO_CATEGORIES",
    "KYVERNO_PROFILE_CATEGORIES",
    "KYVERNO_POLICY_TEMPLATES",
    # Policy helpers
    "get_kyverno_policy",
    "list_kyverno_policies",
    "get_all_kyverno_policies",
    "get_kyverno_policies_by_category",
    # Profile builder functions
    "get_security_profile",
    "get_network_profile",
    "get_registry_profile",
    "get_strict_profile",
    "get_talos_profile",
    "get_pqc_profile",
    "get_all_profile",
    "_KYVERNO_PROFILE_BUILDERS",
    "get_profile",
    "list_profiles",
    "get_profile_policies",
    # Bundle functions
    "get_talos_security_bundle",
    "get_pqc_transition_bundle",
    # Backward-compat shims
    "get_pod_security_baseline",
    "get_pod_security_restricted",
    "get_require_resource_limits",
    "get_require_image_registry",
    "get_require_image_tag",
    "get_require_network_policies",
    "get_disallow_privileged_containers",
    "get_require_persistent_volume_claim",
    "get_pqc_cryptography_readiness",
    "get_pqc_certificate_duration",
    "get_talos_cluster_security",
    "get_require_talos_label",
    "get_require_resource_labels",
    "get_require_pod_disruption_budget",
]
